### ISSUE TITLE
please help to display a dashboard that doesn't show data

### ISSUE THREAD

**Issue by acaaa11** [voidquark/grafana-dashboards#1]
please help to display empty table results

Tested on:
RedHat Enterprise Linux (RHEL) 8 
Grafana 9.3.6 	Tested with Grafana version
Nextcloud 23.0.12

![gambar](https://user-images.githubusercontent.com/103820474/220588383-e1023ae9-c379-4114-ae3a-f0d123165b12.png)

![gambar](https://user-images.githubusercontent.com/103820474/220588161-46213036-92d6-4955-8181-30cf888da831.png)

![gambar](https://user-images.githubusercontent.com/103820474/220588647-b9235771-555e-4935-b79d-4ff7d841198b.png)
![gambar](https://user-images.githubusercontent.com/103820474/220588898-eba823fb-dc63-46c4-9f8a-5d68c6f30144.png)

![gambar](https://user-images.githubusercontent.com/103820474/220589148-dcb35475-6c02-4d00-98ab-10afbfe94401.png)
![gambar](https://user-images.githubusercontent.com/103820474/220589298-ad7f7b6c-a4f0-4106-8b6b-f535d9a70bf7.png)
![gambar](https://user-images.githubusercontent.com/103820474/220589574-5043b4b5-808c-4b46-989d-07c17dd87d41.png)
![gambar](https://user-images.githubusercontent.com/103820474/220589698-f61ccd49-a03c-4738-92c0-e7b916a60a55.png)
![gambar](https://user-images.githubusercontent.com/103820474/220589848-46e908f0-1c20-4376-9f04-2ddb3385db09.png)
![gambar](https://user-images.githubusercontent.com/103820474/220589984-f0c03711-e7d5-4136-8e07-c298c4c48fa6.png)
![gambar](https://user-images.githubusercontent.com/103820474/220590172-92aede45-3482-443f-a189-0e403fd615ae.png)

**Comment by voidquark** [comment]
To me, it looks like your Nextcloud audit logging is not working. Please try the query explorer in Grafana. This way, you can confirm if audit data is available in the Loki instance.

**Comment by acaaa11** [comment]
![gambar](https://user-images.githubusercontent.com/103820474/220861318-c472500c-bc80-4692-946a-42dd17ef00c9.png)

nextcloud audit works, the other tables can display the query results. but those using pattern can't display anything. any other suggestions?

**Comment by voidquark** [comment]
I can give you tips:

1. Open panel which does not work. Go into query inspector. Here you get some valuable insight for diagnostic.
2. Another option is Open Query Explorer like you did in the previous screenshot. Put a query from the panel and adjust variables to hardcoded values ( e.g filename, instance, job ) to match your values. Try querying here and see if you get some results.

I hope it helps.

**Comment by acaaa11** [comment]
looks like the error is in the query pattern. can you help justify it?

![gambar](https://user-images.githubusercontent.com/103820474/221084509-1998ec64-d836-456f-90b6-60b6d0655c89.png)
![gambar](https://user-images.githubusercontent.com/103820474/221084619-b3f38ec4-6565-47b0-b222-4bd48363b7dc.png)
![gambar](https://user-images.githubusercontent.com/103820474/221084784-6a1a5959-d9c4-4850-98b4-ce208c3fd915.png)

**Comment by voidquark** [comment]
After an investigation with @acaaa11 on Telegram. 

**Resolution:** Is required to upgrade Grafana Loki version to at least v2.3+ ...you was using 2.2.1 which does not have `pattern`. This caused the dashboard was not working properly. Updated Loki version info in the blog post.
