### ISSUE TITLE
For more than seven days, loki has not returned any results from these queries.

### ISSUE THREAD

**Issue by impr3ssi0n** [voidquark/grafana-dashboards#5]
Good afternoon. My loki instance doesn't return results in more than 7 days for large queries.
I have tried all the loki configuration settings. Could you please provide your example loki config file?

**Comment by voidquark** [comment]
Hello,

If you need community support or suspect a software bug, please open an issue on the [Loki GitHub repository](https://github.com/grafana/loki).

For assistance with your specific problem, consider visiting [r/Grafana](https://www.reddit.com/r/grafana/) or the official [Grafana Forum](https://community.grafana.com/).

Please note that this repository and its issues are not intended for addressing specific Loki problems. I hope this clarifies the situation.
