### ISSUE TITLE
Question for installation

### ISSUE THREAD

**Issue by rider87** [voidquark/grafana-dashboards#7]
Hey, 
do you have also the whole docker-compose file for it with all the configs (promtail-config...) ?:
https://voidquark.com/blog/promtail-grafana-dashboard/

I would like to need also your dashboard for my wildfly logs, but my dashboard as no entries:

<img width="1482" alt="image" src="https://github.com/user-attachments/assets/16f33033-d252-4a71-b73a-764102fa8b67">

I´m getting in general the logs:
<img width="1600" alt="image" src="https://github.com/user-attachments/assets/1f436d04-3b02-41fd-9890-6a1dfa25add4">

My promtail-config is looking like this:
`server:
  http_listen_port: 9080
  grpc_listen_port: 0
  enable_runtime_reload: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: wildfly-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: wildfly
      __path__: /var/log/wildfly/*log

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: authlog
  static_configs:
  - targets:
      - authlog
    labels:
      job: authlog
      __path__: /logs/auth.log

- job_name: syslog
  static_configs:
  - targets:
      - syslog
    labels:
      job: syslog
      __path__: /logs/syslog`

**Comment by rider87** [comment]
I´m getting also this warning:
![image](https://github.com/user-attachments/assets/604d7fc8-49fc-4a9c-8bf6-def7b73aa4b7)

**Comment by voidquark** [comment]
Here is a corrected and improved version of your text:

Hey, the Promtail dashboard requires Loki, Promtail, and metrics from Promtail. This is a mixed dashboard that needs both loki and prometheus datasources.

I don’t have a setup using Docker Compose, but I recommend checking the Grafana documentation to explore possible deployment options for Promtail, Loki, and Grafana.

This dashboard is specifically tailored for Promtail, so I think there’s a misunderstanding regarding its intended usage. For your `wildfly` application, you would need to build a different dashboard.

Regarding the variable errors, it seems like you are missing the Loki and Prometheus datasources.

If you have questions, please feel free to ask me in the [Telegram](https://t.me/voidquark). The issues in this repository are reserved for bug reports and feature requests.
